using System.Linq;
using System.Text;
using Content.Client.Materials;
using Content.Client.UserInterface.Controls;
using Content.Shared.Lathe;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class LatheMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly LatheSystem _lathe;
    private readonly MaterialStorageSystem _materialStorage;

    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed;
    public event Action<string, int>? RecipeQueueAction;
    public event Action<int>? QueueDeleteAction;
    public event Action<int>? QueueMoveUpAction;
    public event Action<int>? QueueMoveDownAction;
    public event Action? DeleteFabricatingAction;
    public event Action<string?, bool>? OnAutoRecipeToggled;

    public List<ProtoId<LatheRecipePrototype>> Recipes = new();

    public List<ProtoId<LatheCategoryPrototype>>? Categories;

    public ProtoId<LatheCategoryPrototype>? CurrentCategory;

    public EntityUid Entity;

    private string? _activeRecipeId;
    private bool _autoMode;

    // FactoryStation-Edit-Start: Temperature fields
    private float _currentTemperature;
    private float _maxSafeTemperature = 100f;
    // FactoryStation-Edit-End

    public LatheMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
        _lathe = _entityManager.System<LatheSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();

        SearchBar.OnTextChanged += _ =>
        {
            PopulateRecipes();
        };
        AmountLineEdit.OnTextChanged += _ =>
        {
            if (int.TryParse(AmountLineEdit.Text, out var amount))
            {
                if (amount > LatheSystem.MaxItemsPerRequest)
                    AmountLineEdit.Text = LatheSystem.MaxItemsPerRequest.ToString();
                else if (amount < 0)
                    AmountLineEdit.Text = "0";
            }

            PopulateRecipes();
        };

        FilterOption.OnItemSelected += OnItemSelected;

        ServerListButton.OnPressed += a => OnServerListButtonPressed?.Invoke(a);
        DeleteFabricating.OnPressed += _ => DeleteFabricatingAction?.Invoke();

        AutoButton.OnToggled += args =>
        {
            _autoMode = args.Pressed;
            OnAutoRecipeToggled?.Invoke(_activeRecipeId, _autoMode);
        };
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        this.SetInfoFromEntity(_entityManager, Entity);

        if (_entityManager.TryGetComponent<LatheComponent>(Entity, out var latheComponent))
        {
            if (!latheComponent.DynamicPacks.Any())
            {
                ServerListButton.Visible = false;
            }

            AmountLineEdit.SetText(latheComponent.DefaultProductionAmount.ToString());

            // FactoryStation-Edit-Start: Get temperature limits
            _maxSafeTemperature = latheComponent.MaxSafeTemperature;
            // FactoryStation-Edit-End
        }

        MaterialsList.SetOwner(Entity);

        _activeRecipeId = null;
        _autoMode = false;
        AutoButton.Pressed = false;

        // FactoryStation-Edit-Start: Initialize temperature
        UpdateTemperatureDisplay();
        // FactoryStation-Edit-End
    }

    // FactoryStation-Edit-Start: Temperature display
    public void UpdateTemperature(float currentTemp)
    {
        _currentTemperature = currentTemp;
        UpdateTemperatureDisplay();
    }

    private void UpdateTemperatureDisplay()
    {
        TemperatureLabel.Text = $"{_currentTemperature:F1}°C";

        if (_currentTemperature > _maxSafeTemperature * 1.5f)
        {
            TemperatureLabel.FontColorOverride = Color.Red;
            ExplosionWarning.Text = Loc.GetString("lathe-menu-explosion-critical");
            ExplosionWarning.Visible = true;
        }
        else if (_currentTemperature > _maxSafeTemperature)
        {
            TemperatureLabel.FontColorOverride = Color.Orange;
            ExplosionWarning.Text = Loc.GetString("lathe-menu-explosion-warning");
            ExplosionWarning.Visible = true;
        }
        else
        {
            TemperatureLabel.FontColorOverride = Color.Green;
            ExplosionWarning.Visible = false;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (Entity is not { Valid: true })
            return;

        if (_entityManager.TryGetComponent<LatheComponent>(Entity, out var lathe))
        {
            UpdateTemperature(lathe.CurrentTemperature);
        }
    }
    // FactoryStation-Edit-End

    public void PopulateRecipes()
    {
        var recipesToShow = new List<LatheRecipePrototype>();
        foreach (var recipe in Recipes)
        {
            if (!_prototypeManager.Resolve(recipe, out var proto))
                continue;

            if (CurrentCategory != null)
            {
                if (proto.Categories.Count <= 0)
                    continue;

                var validRecipe = proto.Categories.Any(category => category == CurrentCategory);
                if (!validRecipe)
                    continue;
            }

            if (SearchBar.Text.Trim().Length != 0)
            {
                if (_lathe.GetRecipeName(recipe).ToLowerInvariant().Contains(SearchBar.Text.Trim().ToLowerInvariant()))
                    recipesToShow.Add(proto);
            }
            else
            {
                recipesToShow.Add(proto);
            }
        }

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        RecipeCount.Text = Loc.GetString("lathe-menu-recipe-count", ("count", recipesToShow.Count));

        var sortedRecipesToShow = recipesToShow.OrderBy(_lathe.GetRecipeName);
        var oldChildCount = RecipeList.ChildCount;
        _entityManager.TryGetComponent(Entity, out LatheComponent? lathe);

        int idx = 0;
        foreach (var prototype in sortedRecipesToShow)
        {
            var canProduce = _lathe.CanProduce(Entity, prototype, quantity, component: lathe);
            var tooltipFunction = () => GenerateTooltipText(prototype);

            if (idx >= oldChildCount)
            {
                var control = new RecipeControl(_lathe, prototype, tooltipFunction, canProduce, GetRecipeDisplayControl(prototype));
                control.OnButtonPressed += s =>
                {
                    _activeRecipeId = prototype.ID;
                    if (_autoMode && AutoButton.Pressed)
                        OnAutoRecipeToggled?.Invoke(prototype.ID, true);

                    if (!int.TryParse(AmountLineEdit.Text, out var amount) || amount <= 0)
                        amount = 1;
                    RecipeQueueAction?.Invoke(s, amount);
                };
                RecipeList.AddChild(control);
            }
            else
            {
                var child = RecipeList.GetChild(idx) as RecipeControl;
                if (child == null)
                {
                    DebugTools.Assert($"Lathe menu recipe control at {idx} is not of type RecipeControl");
                    continue;
                }

                child.SetRecipe(prototype);
                child.SetTooltipSupplier(tooltipFunction);
                child.SetCanProduce(canProduce);
                child.SetDisplayControl(GetRecipeDisplayControl(prototype));
            }
            idx++;
        }

        for (var childIdx = oldChildCount - 1; idx <= childIdx; childIdx--)
        {
            RecipeList.RemoveChild(childIdx);
        }
    }

    private string GenerateTooltipText(LatheRecipePrototype prototype)
    {
        StringBuilder sb = new();
        var multiplier = _entityManager.GetComponent<LatheComponent>(Entity).MaterialUseMultiplier;

        foreach (var (id, amount) in prototype.Materials)
        {
            if (!_prototypeManager.Resolve(id, out var proto))
                continue;

            var adjustedAmount = SharedLatheSystem.AdjustMaterial(amount, prototype.ApplyMaterialDiscount, multiplier);
            var sheetVolume = _materialStorage.GetSheetVolume(proto);

            var unit = Loc.GetString(proto.Unit);
            var sheets = adjustedAmount / (float)sheetVolume;

            var availableAmount = _materialStorage.GetMaterialAmount(Entity, id);
            var missingAmount = Math.Max(0, adjustedAmount - availableAmount);
            var missingSheets = missingAmount / (float)sheetVolume;

            var name = Loc.GetString(proto.Name);

            string tooltipText;
            if (missingSheets > 0)
            {
                tooltipText = Loc.GetString("lathe-menu-material-amount-missing", ("amount", sheets), ("missingAmount", missingSheets), ("unit", unit), ("material", name));
            }
            else
            {
                var amountText = Loc.GetString("lathe-menu-material-amount", ("amount", sheets), ("unit", unit));
                tooltipText = Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", amountText));
            }

            sb.AppendLine(tooltipText);
        }

        var desc = _lathe.GetRecipeDescription(prototype);
        if (!string.IsNullOrWhiteSpace(desc))
            sb.AppendLine(Loc.GetString("lathe-menu-description-display", ("description", desc)));

        if (sb.Length > 0)
            sb.Remove(sb.Length - 1, 1);

        return sb.ToString();
    }

    public void UpdateCategories()
    {
        var currentCategories = new List<ProtoId<LatheCategoryPrototype>>();
        foreach (var recipeId in Recipes)
        {
            var recipe = _prototypeManager.Index(recipeId);

            if (recipe.Categories.Count <= 0)
                continue;

            foreach (var category in recipe.Categories)
            {
                if (currentCategories.Contains(category))
                    continue;

                currentCategories.Add(category);
            }
        }

        if (Categories != null && (Categories.Count == currentCategories.Count || !Categories.All(currentCategories.Contains)))
            return;

        Categories = currentCategories;
        var sortedCategories = currentCategories
            .Select(p => _prototypeManager.Index(p))
            .OrderBy(p => Loc.GetString(p.Name))
            .ToList();

        FilterOption.Clear();
        FilterOption.AddItem(Loc.GetString("lathe-menu-category-all"), -1);
        foreach (var category in sortedCategories)
        {
            FilterOption.AddItem(Loc.GetString(category.Name), Categories.IndexOf(category.ID));
        }

        FilterOption.SelectId(-1);
    }

    public void PopulateQueueList(IReadOnlyCollection<LatheRecipeBatch> queue)
    {
        var oldChildCount = QueueList.ChildCount;

        var idx = 0;
        foreach (var batch in queue)
        {
            var recipe = _prototypeManager.Index(batch.Recipe);

            var itemName = _lathe.GetRecipeName(batch.Recipe);
            string displayText;
            if (batch.ItemsRequested > 1)
                displayText = Loc.GetString("lathe-menu-item-batch", ("index", idx + 1), ("name", itemName), ("printed", batch.ItemsPrinted), ("total", batch.ItemsRequested));
            else
                displayText = Loc.GetString("lathe-menu-item-single", ("index", idx + 1), ("name", itemName));

            if (idx >= oldChildCount)
            {
                var queuedRecipeBox = new QueuedRecipeControl(displayText, idx, GetRecipeDisplayControl(recipe));
                queuedRecipeBox.OnDeletePressed += s => QueueDeleteAction?.Invoke(s);
                queuedRecipeBox.OnMoveUpPressed += s => QueueMoveUpAction?.Invoke(s);
                queuedRecipeBox.OnMoveDownPressed += s => QueueMoveDownAction?.Invoke(s);
                QueueList.AddChild(queuedRecipeBox);
            }
            else
            {
                var child = QueueList.GetChild(idx) as QueuedRecipeControl;

                if (child == null)
                {
                    DebugTools.Assert($"Lathe menu queued recipe control at {idx} is not of type QueuedRecipeControl");
                    continue;
                }

                child.SetDisplayText(displayText);
                child.SetIndex(idx);
                child.SetDisplayControl(GetRecipeDisplayControl(recipe));
            }
            idx++;
        }

        for (var childIdx = oldChildCount - 1; idx <= childIdx; childIdx--)
        {
            QueueList.RemoveChild(childIdx);
        }
    }

    public void SetQueueInfo(ProtoId<LatheRecipePrototype>? recipeProto)
    {
        FabricatingContainer.Visible = recipeProto != null;
        if (recipeProto == null)
            return;

        var recipe = _prototypeManager.Index(recipeProto.Value);

        FabricatingDisplayContainer.Children.Clear();
        FabricatingDisplayContainer.AddChild(GetRecipeDisplayControl(recipe));

        NameLabel.Text = _lathe.GetRecipeName(recipe);
    }

    public Control GetRecipeDisplayControl(LatheRecipePrototype recipe)
    {
        if (recipe.Icon != null)
        {
            var textRect = new TextureRect();
            textRect.Texture = _spriteSystem.Frame0(recipe.Icon);
            return textRect;
        }

        if (recipe.Result is { } result)
        {
            var entProtoView = new EntityPrototypeView();
            entProtoView.SetPrototype(result);
            return entProtoView;
        }

        return new Control();
    }

    private void OnItemSelected(OptionButton.ItemSelectedEventArgs obj)
    {
        FilterOption.SelectId(obj.Id);
        if (obj.Id == -1)
        {
            CurrentCategory = null;
        }
        else
        {
            CurrentCategory = Categories?[obj.Id];
        }
        PopulateRecipes();
    }
}
